spring:
  cloud:
    config:
      label: master
      name: app1 #需要从github上读取的资源名称，注意没有yml后缀名
      profile: test   #本次访问的配置项
      uri: http://localhost:8888  #本微服务启动后先去找3344号服务，通过SpringCloudConfig获取GitHub的服务地址